export interface DeviceCategories {
  title: string;
  items: string[];
}

export const DEVICE_CATEGORIES: DeviceCategories[] = [
  {
    title: "Smartphones & Tablettes",
    items: [
      "iPhone 15 / 14 / 13 / 12 / 11 / X / SE",
      "iPhone 16-serie en nieuwere iOS-modellen",
      "iPad, iPad Air, iPad Mini & iPad Pro",
      "iOS en iPadOS 13+ IPTV-apps",
      "Samsung Galaxy S / Z Fold / Z Flip / Note",
      "Google Pixel smartphones",
      "OnePlus, Xiaomi, Redmi, Poco, Oppo, Realme",
      "Motorola, Nokia, Nothing, Sony Xperia, ASUS ROG",
      "Huawei, Honor en HarmonyOS-apparaten via player-apps",
      "Android smartphones met Android 7+",
      "Samsung Galaxy Tab",
      "Lenovo Tab, Xiaomi Pad, OnePlus Pad, Oppo Pad",
      "Huawei MatePad en Honor Pad",
      "Amazon Fire HD Tablets",
      "IPTV Smarters, GSE IPTV, XCIPTV, Televizo",
      "TiviMate Companion, OTT Navigator, IPTV Extreme",
    ],
  },
  {
    title: "Smart TV's & Streaming",
    items: [
      "Samsung Smart TV / Tizen OS (2016+)",
      "Samsung Tizen 2.4, 3.0, 4.0, 5.0, 6.0, 7.0+",
      "LG Smart TV / WebOS 3.0, 4.0, 5.0, 6.0, 22, 23, 24+",
      "Sony Bravia Google TV & Android TV",
      "Sony Bravia 2015+ Android TV en 2021+ Google TV",
      "Philips Saphi, Android TV & Google TV",
      "Philips Ambilight TV, Android TV, Google TV",
      "Panasonic Smart TV / My Home Screen",
      "Panasonic Android TV, Fire TV en OLED/LCD series",
      "Hisense VIDAA & Google TV",
      "Hisense VIDAA U3, U4, U5, U6, U7+",
      "TCL Roku TV, Android TV & Google TV",
      "TCL C/P/S-series, Roku TV en Google TV",
      "Sharp Android TV, Google TV & Aquos",
      "Toshiba Smart TV, Fire TV & Android TV",
      "Grundig, JVC, Hitachi, Vestel, Telefunken Smart TV",
      "Nokia Smart TV, Xiaomi TV, Metz, Loewe, Blaupunkt",
      "Roku TV, Fire TV Edition en Android TV Edition",
      "Smart TV's met browser of M3U/IPTV-app ondersteuning",
      "Smart IPTV, IBO Player, SET IPTV, Net IPTV",
      "SS IPTV, DuplexPlay, Flix IPTV, SmartOne IPTV",
      "Hot IPTV, Smart STB, Bay IPTV, Room IPTV",
    ],
  },
  {
    title: "Computers & Laptops",
    items: [
      "Windows 11 / 10 PC & laptops",
      "Windows 8.1 en Windows 7 via VLC/Kodi waar ondersteund",
      "Microsoft Surface Pro, Laptop & Studio",
      "macOS MacBook, iMac, Mac Mini & Mac Studio",
      "macOS Sonoma, Ventura, Monterey en oudere ondersteunde versies",
      "Linux Ubuntu, Debian, Fedora, Mint",
      "Arch, Manjaro, Pop!_OS, OpenSUSE en Raspberry Pi OS",
      "Chromebook & ChromeOS",
      "All-in-one PC's, gaming laptops en workstations",
      "Mini PC, Intel NUC, Beelink, Geekom",
      "Raspberry Pi 3/4/5 met Kodi, VLC of browser",
      "VLC, Kodi, MyIPTV Player, IPTV Smarters",
      "Web player via Chrome, Edge, Firefox, Safari",
    ],
  },
  {
    title: "Appareils de Streaming",
    items: [
      "Amazon Fire TV Stick (alle versies)",
      "Fire TV Stick Lite, 4K, 4K Max & Cube",
      "Google Chromecast 3, Chromecast Ultra",
      "Chromecast met Google TV HD & 4K",
      "Apple TV 4K & HD",
      "Apple TV tvOS 13+ via geschikte IPTV-apps",
      "Roku Express, Premiere, Ultra & Streaming Stick",
      "Roku TV en Roku OS apparaten met M3U/browser opties",
      "Xiaomi Mi Box & Stick",
      "Xiaomi TV Stick 4K, Mi Box S 2nd Gen",
      "Nokia Streaming Box",
      "Strong Leap, Homatics Box, Mecool, Ugoos",
      "Nvidia Shield TV & Shield TV Pro",
      "Nvidia Shield 2015, 2017, 2019 Tube & Pro",
      "Realme TV Stick, Dynalink, TiVo Stream 4K",
      "Onn Android TV Box, Walmart Google TV Box",
      "Android TV Boxen met Android 7+",
      "Amlogic S905/S912/S922 boxen met IPTV-player",
    ],
  },
  {
    title: "Box TV",
    items: [
      "MAG 250, 254, 256, 322, 324, 420, 520",
      "MAG 524, 540, 544, 555 en Ministra/Stalker portals",
      "Formuler Z7, Z8, Z10, Z11, Z Mini, GTV",
      "Formuler Z Alpha, Z Nano, Z10 Pro Max, Z11 Pro Max",
      "BuzzTV XRS, X5, Classic, Vidstick",
      "BuzzTV XR/XR4000/XR4500/X5 AI series",
      "Dreambox DM One, DM Two, DM920",
      "VU+ Zero, Uno, Duo, Solo, Ultimo",
      "Zgemma H9, H11, i55, H7",
      "Amiko, Octagon, Edision, Gigablue",
      "Mutant, Axas, Qviart, Dinobot, Wetek",
      "Enigma2, XtreamTV, Stalker Portal, Ministra",
      "TVIP, Infomir, AuraHD, Openbox",
      "Android STB's met MyTVOnline, Stalker of Xtream Codes",
    ],
  },
  {
    title: "Consoles de Jeux",
    items: [
      "PlayStation 5 & PlayStation 4",
      "PlayStation 3 via DLNA/browser waar beschikbaar",
      "Xbox Series X | S",
      "Xbox One & One S/X",
      "Xbox 360 via media player",
      "Nintendo Switch via browser of capture setup",
      "Nintendo Wii U via browser waar beschikbaar",
      "Steam Deck via browser, VLC of Kodi",
      "ROG Ally / Legion Go Windows handhelds",
      "AYANEO, MSI Claw en andere Windows handhelds",
    ],
  },
  {
    title: "Lecteurs Multimedia",
    items: [
      "Kodi (op elk apparaat)",
      "VLC Media Player",
      "VLC op Windows, macOS, Linux, Android en iOS",
      "Plex, Jellyfin & Emby",
      "Perfect Player & IPTV Smarters",
      "TiviMate, OTT Navigator, XCIPTV",
      "GSE Smart IPTV, IBO Player, Televizo",
      "ProgTV, Lazy IPTV, IPTV Extreme",
      "Smarters Pro, SmartOne IPTV, Net IPTV",
      "M3U playlist, Xtream Codes API, Stalker portal",
      "EPG XMLTV, Catch-up en multi-screen waar app ondersteunt",
      "M3U8, HLS, TS-streams en externe players",
    ],
  },
  {
    title: "Browsers",
    items: [
      "Google Chrome",
      "Chrome desktop, Android en ChromeOS",
      "Safari",
      "Safari macOS en iOS/iPadOS",
      "Mozilla Firefox",
      "Microsoft Edge",
      "Opera & Brave",
      "Samsung Internet",
      "Android WebView browsers",
      "Silk Browser op Fire TV",
      "TV-browser op LG, Samsung, Philips en Sony",
      "Web player op desktop, tablet en mobiel",
      "Chromium browsers zoals Vivaldi, Arc en Yandex",
      "Browsers met HLS/M3U8 ondersteuning",
    ],
  },
];
